AllCops:
  TargetRubyVersion: 2.5

Lint/UnusedMethodArgument:
  Exclude:
    - lambda_function.rb

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Exclude:
    - crawler.rb

Metrics/LineLength:
  Max: 120
